### ISSUE TITLE
[FEAT]: Stats

### ISSUE THREAD

**Issue by ammar-ahmed22** [ammar-ahmed22/flowtimer#7]
**Is your feature request related to a problem? Please describe.**
Not really, want to be able to track metrics.

**Describe the solution you'd like**
A stats page that shows various metrics:
- Central bar graph shows for a specific day (current day, can change it to different days or week, month), the focus time (minutes) vs. time of day (hour)
    + i.e. worked for 25 minutes from 9:47 am to 10:12am. There will be a bar for 12 minutes at the 9-10am section and a bar for 13 minutes at the 10-11am section
- On the side, single values for total focus time for the day, week, month, all time, longest focus time for the day, week, month, all time, average focus time for the day, week, month, all time, total break time for day, week, month, all time, average break time for day, week, month, all time
- On the bottom, heat map similar to GitHub commits showing for each day the amount of focus time
     + Based on the average and the max average for all days, max average would be opaque, lower average would be more transparent

**Additional context**
N/A

**Comment by ammar-ahmed22** [comment]
To start, everything will be persisted in local storage as with tasks. Later on, might introduce auth and user accounts to persist across devices.

**Comment by ammar-ahmed22** [comment]
# Tasks
- [x] Central bar graph
    + [x] Select different dates 
- [x] Single values
    + [x] Total focus time
    + [x] Longest focus time
    + [x] Average focus time
- [ ] Heat map
